  Nm_erro = new Array();
   Nm_erro[1] = "Número Inválido!!";
   Nm_erro[2] = "Valor Inválido!!";
   Nm_erro[3] = "O sinal negativo deve ficar a esquerda do valor!!";
   Nm_erro[4] = "Quantidade de dígitos superior ao previsto de";
   Nm_erro[41] = "Inteiros e";
   Nm_erro[42] = "Decimais";
   Nm_erro[5] = "Campo com dados não numéricos!!";
   Nm_erro[6] = "Valor Inválido:";
   Nm_erro[61] = "Min =";
   Nm_erro[62] = "Max =";
   Nm_erro[7] = "CIC Inválido!!";
   Nm_erro[8] = "CNPJ Inválido!!";
   Nm_erro[9] = "Data Inválida:";
   Nm_erro[91] = "Dia";
   Nm_erro[92] = "Mes";
   Nm_erro[93] = "Data mínima";
   Nm_erro[94] = "Data máxima";
   Nm_erro[10] = "Hora Inválida:";
   Nm_erro[101] = "Hora";
   Nm_erro[102] = "Minuto";
   Nm_erro[103] = "Segundo";
   Nm_erro[104] = "Décimo de segundo";
   Nm_erro[11] = "CEP Inválido!!";
   Nm_erro[12] = "Dados digitados superam o máximo permitido de";
   Nm_erro[13] = "Dados Inválidos:";
   Nm_erro[14] = "Email Inválido:";
   Nm_erro[141] = "Faltou '@';";
   Nm_erro[142] = "Tem mais de um '@';";
   Nm_erro[143] = "Faltou Login;";
   Nm_erro[144] = "Sufixo faltando '.';";
   Nm_erro[145] = "Sufixo iniciando com '.';";
   Nm_erro[146] = " Sufixo terminando com '.';";
   Nm_erro[15] = "Cartão Inválido!!";
   Nm_erro[501] = "Faltou definir um nome para o Form!!";
   Nm_erro[502] = "Faltou definir um nome para este objeto do Form!!";
   Nm_erro[503] = "Campo de preenchimento obrigatório!!";
   Nm_erro[504] = " - Deseja corrigir?";

//-------- Mens USR